### ISSUE TITLE
Fix compatibility with 3.9

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/nlp-pie-taggers#43]
There seem to be a huge problem of compatibility with python3.9. Needs investigation

**Comment by crazyjeannot** [comment]
Hi there ! 
Python 3.9.2

I am working on the distant machine from the lattice lab, having python 3.9.2 installed.

```  python
jbarre@atropos:~/lemmatizers$ virtualenv -p python3 pie_env
created virtual environment CPython3.9.2.final.0-64 in 157ms
  creator CPython3Posix(dest=/home/jbarre/lemmatizers/pie_env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jbarre/.local/share/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.6.3, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
```

``` python
jbarre@atropos:~/lemmatizers$ source pie_env/bin/activate
```
```python
(pie_env) jbarre@atropos:~/lemmatizers$ pip install pie-extended
Collecting pie-extended
  Using cached pie_extended-0.0.41-py2.py3-none-any.whl (68 kB)
Collecting unidecode>=1.1.1
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting PaPie==0.3.9
  Using cached PaPie-0.3.9-py2.py3-none-any.whl (85 kB)
Collecting scipy<1.6.0
  Using cached scipy-1.5.4-cp39-cp39-manylinux1_x86_64.whl (25.8 MB)
Collecting regex
  Using cached regex-2022.10.31-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (769 kB)
Collecting autodisambiguator<1.0.0,>=0.0.1
  Using cached autodisambiguator-0.0.1-py2.py3-none-any.whl (11 kB)
Collecting colorama>=0.4.4
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting click<8.0,>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting numpy<1.18.0
  Using cached numpy-1.17.5-cp39-cp39-linux_x86_64.whl
Collecting requests>=2.25.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting pyyaml==5.1b3
  Using cached PyYAML-5.1b3-cp39-cp39-linux_x86_64.whl
Collecting scikit-learn<0.23.0,>=0.19.1
  Using cached scikit-learn-0.22.2.post1.tar.gz (6.9 MB)
  Preparing metadata (setup.py) ... done
Collecting lxml>=4.2.1
  Using cached lxml-4.9.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
Collecting gensim>=3.4.0
  Using cached gensim-4.3.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (24.0 MB)
Collecting tqdm>=4.23.3
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting terminaltables==3.1.0
  Using cached terminaltables-3.1.0-py3-none-any.whl
Collecting typing<4.0
  Using cached typing-3.7.4.3-py3-none-any.whl
Collecting JSON-minify>=0.3.0
  Using cached JSON_minify-0.3.0-py2.py3-none-any.whl (5.2 kB)
Collecting termcolor>=1.1.0
  Using cached termcolor-2.2.0-py3-none-any.whl (6.6 kB)
Collecting torch<=1.7.1,>=1.3.1
  Using cached torch-1.7.1-cp39-cp39-manylinux1_x86_64.whl (776.8 MB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (198 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting gensim>=3.4.0
  Using cached gensim-4.2.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (24.0 MB)
Collecting smart-open>=1.8.1
  Using cached smart_open-6.3.0-py3-none-any.whl (56 kB)
Collecting joblib>=0.11
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/setup.py", line 195, in check_package_status
          module = importlib.import_module(package)
        File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/setup.py", line 303, in <module>
          setup_package()
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/setup.py", line 291, in setup_package
          check_package_status('numpy', NUMPY_MIN_VERSION)
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/setup.py", line 219, in check_package_status
          raise ImportError("{} is not "
      ImportError: numpy is not installed.
      scikit-learn requires numpy >= 1.11.0.
      Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
Installing collected packages: terminaltables, JSON-minify, charset-normalizer, urllib3, unidecode, typing-extensions, typing, tqdm, termcolor, smart-open, regex, pyyaml, numpy, lxml, joblib, idna, colorama, click, certifi, autodisambiguator, torch, scipy, requests, scikit-learn, gensim, PaPie, pie-extended
  Running setup.py install for scikit-learn ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for scikit-learn did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/sklearn/_build_utils/__init__.py", line 32, in _check_cython_version
          import Cython
      ModuleNotFoundError: No module named 'Cython'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/setup.py", line 303, in <module>
          setup_package()
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/setup.py", line 299, in setup_package
          setup(**metadata)
        File "/home/jbarre/lemmatizers/pie_env/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
          config = configuration()
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/setup.py", line 180, in configuration
          _check_cython_version()
        File "/tmp/pip-install-a28201qf/scikit-learn_aad388de80b4413b8920fd39503448f8/sklearn/_build_utils/__init__.py", line 35, in _check_cython_version
          raise ModuleNotFoundError(message)
      ModuleNotFoundError: Please install Cython with a version >= 0.28.5 in order to build a scikit-learn from source.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> scikit-learn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

This might illustrate the **"huge problem"** with python 3.9

Your tips might be to set python to 3.8, and rerun ?
Something like that :

``` python
jbarre@atropos:~$ virtualenv -p python3.8 pie_env
```

**Comment by PonteIneptique** [comment]
Yup, 3.8 or 3.7 should work.
It will be fixed in the coming weeks, as I now have time to deal with such things...

**Comment by PonteIneptique** [comment]
Should be compatible with 3.8 and up ;)_
